### ISSUE TITLE
Regelfälle für Version 1 bestimmen

### ISSUE THREAD

**Issue by zeekrey** [zeekrey/buergergeldrechner-leipzig#4]
Für die ersten Version sollen die häufigsten Bürgergeld-Regelfälle identifiziert und beschrieben werden.

**Akzeptanzkriterien**
- Es wurden die _n_ häufigsten Regelfälle identifiziert
- Diese sind beschrieben durch
  - Merkmale der Bedarfsgemeinschaft
  - Ausgaben
  - Einnahmen
  - Potentieller Bürgergeldbedarf

**Comment by zeekrey** [comment]
Folgende Regelfälle werden hier beschrieben: https://www.bmas.de/DE/Arbeit/Grundsicherung-Buergergeld/Leistungen-und-Bedarfe-im-Buergergeld/artikelseite-leistungen-und-bedarfe-im-buergergeld.html#doc5790d24f-5902-41f7-ab75-d31bf87ea183bodyText6

**Comment by tmic83** [comment]
**Single (mit Einkommen)**

Regelbedarf Antragsteller - 563,00
Unterkunft und Heizung - 516,00
Bedarf insgesamt: 1.079,00
EK brutto: 1.200,00
EK netto: 950,00 
bei diesem EK ergibt sich ein Freibetrag: 348,00
Zu berücksichtigendes Einkommen: 602,00
Bürgergeldanspruch: 477,00

Freibetragsrechner https://www.sgb2.info/DE/Service/Freibetragsrechner/freibetragsrechner.html
Erklärung Freibetragsberechnung
https://www.bmas.de/DE/Arbeit/Grundsicherung-Buergergeld/Leistungen-und-Bedarfe-im-Buergergeld/einkommen-und-vermoegen.html#docc9c1b29c-2e48-44e2-bd73-66901a9fe37fbodyText1

**Comment by tmic83** [comment]
**(Ehe-)Paar mit Einkommen**

Regelbedarf Partner 1 - 506,00
Regelbedarf Partner 2 - 506,00
Kaltmiete: 350,00
Nebenkosten: 66,00
Heizkosten: 100,00
EK brutto: 2.100,00
EK netto: 1.700
bei diesem EK ergibt sich ein Freibetrag: 348,00
Zu berücksichtigendes Einkommen: 602,00
Bürgergeldanspruch: 477,00

**Comment by tmic83** [comment]
### **(Ehe-)Paar mit Kind**

Regelbedarf Partner 1: 506,00
Regelbedarf Partner 2: 506,00
Regelbedarf 4-jähriges Kind: 357,00
Kaltmiete: 550,00
Nebenkosten: 100,00
Heizkosten: 150,00
**Bedarf insgesamt: 2.169,00**
EK brutto: 2.100,00
EK netto: 1.700,00
bei diesem EK ergibt sich ein Freibetrag: 378,00
Zu berücksichtigendes Einkommen: 1.322,00
Kindergeld: 250,00
**Bürgergeldanspruch: 597,00**

**Comment by tmic83** [comment]
(Ehe-)Paar mit 2 Kindern

Regelbedarf Partner 1: 506,00
Regelbedarf Partner 2: 506,00
Regelbedarf 19-Jähriges Kind 1 in Schule: 451,00
Regelbedarf 4-jähriges Kind 2: 357,00
Kaltmiete: 650,00
Nebenkosten: 100,00
Heizkosten: 150,00
**Bedarf insgesamt: 2.720,00**
Partner 1 EK brutto: 2.100,00
Partner 1 EK netto: 1.700,00
bei diesem EK ergibt sich ein Freibetrag für Partner 1: 378,00
Zu berücksichtigendes Einkommen für Partner 1: 1.322,00
Arbeitslosengeld Partner 2: 1.200 mtl.
Kindergeld Kind 1+2: 500,00
Pauschale für angemessene private Versicherungen für Kind 1: 30,00 (=Freibetrag)
**Bürgergeldanspruch: -242,00**

**Comment by tmic83** [comment]
0

**Comment by zeekrey** [comment]
Hey zusammen,

ich habe ein paar Fragen zum Einkommen:

1. Das zu berücksichtigende Einkommen bezieht sich immer auf den kompletten Haushalt, korrekt?
2. Im letzten Beispiel bezieht der Partner 2 Arbeitslosengeld. Wie wollen wir das erfassen? Habt ihr da Ideen?
3. Wie sollen wir die Pauschale für angemessene private Versicherung der Kinder abfragen?

**Comment by tmic83** [comment]
Hallo,

zu 1. 
in den benannten Beispielen bezieht sich das zu berücksichtigende Einkommen auf alle Mitglieder der Bedarfsgemeinschaft. 
Gerne möchte ich dir allgemein zu Berechnung gerne die [Fachlichen Weisungen zu § 9 SGB II](https://www.arbeitsagentur.de/ueber-uns/veroeffentlichungen/gesetze-und-weisungen/sgbii-grundsicherung) ans Herz legen (ab 3. Berechnung)

zu 2.
So ganz verstehe ich möglicherweise die Frage nicht...
Arbeitslosengeld (≠ Bürgergeld) ist eine Einkommensart, wie viele andere noch mögliche Einkommen, die relvant für den Rechner sein werden (bspw. Krankengeld, Verletztengeld, Unterhaltsvorschuss, Kinderzuschlag, Wohngeld, Elterngeld).
Sofern eines der BG-Mitglieder eine der benannten Einkommensarten hat, muss die Möglichkeit bestehen, dass diese erfasst werden kann (einfaches Feld zur Erfassung eines Betrags in Euro [xx.xxx,xx Euro]

zu 3.
vorab Definition: "Vom Einkommen eines jeden **volljährigen** Mitglieds einer BG werden für angemessene private Versicherungen pauschal 30,00 Euro monatlich abgesetzt. Die Pauschale kann auch vom Kindergeld eines 18- bis 24-jährigen Kindes abgesetzt werden. Auch auf Nachweis können keine höheren Beiträge berücksichtigt werden. "
Es ist aus meiner Sicht ausreichend, wenn die Pauschale im "Hintergrund" bei jedem volljährigen BG-Mitglied abgezogen wird, sofern Einkommen erzielt wird. Ist dieses Einkommen jedoch Einkommen aus Erwerbstätigkeit, dann fließt die Pauschale in den Grundfreibetrag auf das Einkommen mit ein.

Für schnelle Rückfragen deinerseits, gerne auch mal unter 0176-66621491.

MfG, Micha

**Comment by tmic83** [comment]
Anbei, wie besprochen, die gängigsten Einkommensarten:

Einkommen aus abhängiger Erwerbstätigkeit 
Einkommen aus selbständiger Erwerbstätigkeit 
Kindergeld [vorbelegt, wie besprochen mit 250 Euro je Kind]
Unterhaltsvorschuss 
Kindesunterhalt
Sonstiger Unterhalt 
Arbeitslosengeld 
Krankengeld
Wohngeld 
Kinderzuschlag 
Elterngeld 
Übergangsgeld Rentenversicherung 
Altersrente
Witwenrente/Witwerrente 
Waisenrente 
Verletztenrente 
Unfallrente 
Rente wegen Erwerbsminderung 
Sonstige Rente 
Unterhaltsbeitrag aus Meisterbafög 
Kurzarbeitergeld 
BAföG
Berufsausbildungsbeihilfe 
Ausbildungsgeld
Steuerfreie nebenberufliche Tätigkeit 
Freiwilligendienst, Soziales/Ökologisches Jahr
Sonstiges Einkommen 

Ggf. müssen wir dann als Gruppe entscheiden, vor welcher EK-Art wir den Rechner "bewahren" wollen...?!

LG, Micha

**Comment by TiSchJC** [comment]
Hier meine Anmerkungen dazu:
Einkommen aus abhängiger Erwerbstätigkeit
Einkommen aus selbständiger Erwerbstätigkeit
Kindergeld [vorbelegt, wie besprochen mit 250 Euro je Kind]
Unterhaltsvorschuss
Kindesunterhalt > Unterhalt
Sonstiger Unterhalt > Unterhalt
Arbeitslosengeld
Krankengeld
Wohngeld
Kinderzuschlag
Elterngeld
Übergangsgeld Rentenversicherung - streichen
Altersrente > Rente
Witwenrente/Witwerrente > Rente
Waisenrente > Rente
Verletztenrente > Rente
Unfallrente > Rente
Rente wegen Erwerbsminderung > Rente, ggf. Info-Feld mit Beispielen
Sonstige Rente
Unterhaltsbeitrag aus Meisterbafög
Kurzarbeitergeld
BAföG
Berufsausbildungsbeihilfe
Ausbildungsgeld - streichen
Steuerfreie nebenberufliche Tätigkeit
Freiwilligendienst, Soziales/Ökologisches Jahr
Sonstiges Einkommen (Geldgeschenke)
